name: workout_notebook
description: Workout notebook
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^8.1.2
  built_collection: ^5.1.1
  redux: ^5.0.0
  redux_epics: ^0.15.0
  flutter_redux: ^0.8.2

dev_dependencies:
  flutter_lints: ^1.0.0
  built_value_generator: ^8.1.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true